fix(participant entity): SJIP-471 display all data category in data files table
include-dcc/include-portal-ui pull request #320
Opened 2023-06-14 20:29 UTC by AltefrohneGaelle

# FIX: TITLE

- closes [SJIP-471](https://d3b.atlassian.net/browse/SJIP-471)

## Description
In participant entity, category in file table doesn't display all data categories present in the app.
Fix progress bar display.

Same for exprimental strategy (not in the ticket but same place and behavior)

## Validation

- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
### Before
- Without file
![image](https://github.com/include-dcc/include-portal-ui/assets/133775440/7f1cf981-4ed4-4799-a01c-8ab41f7daa78)

- With file in each data category
![image](https://github.com/include-dcc/include-portal-ui/assets/133775440/2a6a7b72-359e-4cc2-9888-3892ec0ba914)

- With file not in all data category
![image](https://github.com/include-dcc/include-portal-ui/assets/133775440/e9084b8d-d7e2-4139-8b0f-957a3e3a282c)

### After

- Without file
![image](https://github.com/include-dcc/include-portal-ui/assets/133775440/0aee01ed-b0cd-46e1-a816-d76b8e33785f)

- With file in each data category
![image](https://github.com/include-dcc/include-portal-ui/assets/133775440/48d4b10e-1011-4e5b-8270-327c3ca288e0)

- With file not in all data category
![image](https://github.com/include-dcc/include-portal-ui/assets/133775440/d26b9c46-1f08-4582-86e2-5026229518b3)

2023-06-14 20:56 UTC, evans-g-crsj commented on src/views/ParticipantEntity/utils/files.tsx
> +    if (!file.data_category) {
personnellement, je n'aime pas `continue`. Tu peux le garder, mais il y a d'autres options que tu peux envisager:
- enrober ton code dans un if (file.data_category) { ...logique...}
- faire un filter sur les files `files.filter(f => !!f.data_category)` et boucler sur ce resultat

2023-06-14 21:02 UTC, evans-g-crsj commented on src/views/ParticipantEntity/utils/files.tsx
>    const filesInfosData: IFileInfoByType[] = [];
renommer la variable filesInfoData (pas de S à info)

2023-06-14 21:27 UTC, evans-g-crsj requested changes

2023-06-14 21:27 UTC, evans-g-crsj commented on src/views/ParticipantEntity/utils/files.tsx
>      const filesFound = files.filter(({ data_category }) => data_category === file.data_category);
tu peux le calculer dans le if

2023-06-14 21:27 UTC, evans-g-crsj commented on src/views/ParticipantEntity/utils/files.tsx
> +        proportion_of_files: 0,
regarde dans si le % est bien formatté

2023-06-15 12:24 UTC, AltefrohneGaelle commented on src/views/ParticipantEntity/utils/files.tsx
> +    if (!file.data_category) {
oui en effet je ne sais pas pourquoi j'ai fait ca comme ca

2023-06-15 12:25 UTC, AltefrohneGaelle commented on src/views/ParticipantEntity/utils/files.tsx
>    const filesInfosData: IFileInfoByType[] = [];
pas de soucis je l'enleve mais je me demande si ce n'etait pas pour signifier que c'est une liste

2023-06-15 16:24 UTC, evans-g-crsj approved these changes

2023-06-15 16:29 UTC, merged