fix(saved set): SJIP-488 update icons
include-dcc/include-portal-ui pull request #328
Opened 2023-06-20 20:47 UTC by AltefrohneGaelle

# FIX : Change icon according to type set

- closes [SJIP-488](https://d3b.atlassian.net/browse/SJIP-488)

## Description

Before we have only one icon for each type of set. According to the set type we want a different icon.

## Validation

- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
### Before
![Screenshot from 2023-06-20 16-40-24](https://github.com/include-dcc/include-portal-ui/assets/133775440/5cbfddde-8c68-4272-8b56-3c8cff219372)
![Screenshot from 2023-06-20 16-40-38](https://github.com/include-dcc/include-portal-ui/assets/133775440/838a6a13-5dca-438c-b1f0-b5d5a350dbf5)
![Screenshot from 2023-06-20 16-33-39](https://github.com/include-dcc/include-portal-ui/assets/133775440/e16b7423-58e0-4e9a-9ca2-511f7a511ea6)

### After
![Screenshot from 2023-06-20 16-32-21](https://github.com/include-dcc/include-portal-ui/assets/133775440/a835ac2c-fc1e-43ff-b0ef-f6d12f613836)
![Screenshot from 2023-06-20 16-32-36](https://github.com/include-dcc/include-portal-ui/assets/133775440/da8c5f8f-3f3e-4154-a5ac-d1bbfa1527df)
![Screenshot from 2023-06-20 16-32-50](https://github.com/include-dcc/include-portal-ui/assets/133775440/dce67f10-0a6e-4c8f-84bc-d0db1a9d8568)
![Screenshot from 2023-06-20 16-39-12](https://github.com/include-dcc/include-portal-ui/assets/133775440/f9bdc354-36f8-4127-bad8-3e28c7141df4)

2023-06-20 21:08 UTC, evans-g-crsj requested changes

2023-06-20 21:08 UTC, evans-g-crsj commented on src/views/DataExploration/components/SetsManagementDropdown/UserSetForm/index.tsx
> +      break;
c'est mal de mettre un `break` dans clause `default`. Elle devrait avoir une valeur par défaut (une icone, null, undefined, ...) qui est cohérente avec le type de la valeur de retour
personnellement (facultatif), j'irais avec une cascade de if

2023-06-21 12:09 UTC, AltefrohneGaelle commented on src/views/DataExploration/components/SetsManagementDropdown/UserSetForm/index.tsx
> +      break;
je vais conserver le switch qui pour moi est plus performant surtout que ce n'est qu'un check d'egalite si ca te va.

2023-06-21 13:31 UTC, evans-g-crsj approved these changes

2023-06-21 14:45 UTC, merged